services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  pgdata:

networks:
  spring-network:
